name: ANARI-Docs CI
on:
  workflow_dispatch:
  push:
    branches: [main, next_release]
  pull_request:
    branches: [main, next_release]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker run --network=host --user ${uid}:${gid} --rm -v ${PWD}:/vulkan khronosgroup/docker-images@sha256:9f5add2758a383ba329bc8c4b819dea9fb695ee629b05b7da4739ddf81d39073 make -C /vulkan html pdf
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: ANARI-Docs
          path: |
            out/html
            out/pdf
          if-no-files-found: error
  attach-html-doc-to-pr:
    runs-on: ubuntu-latest
    needs: build-docs
    if: "${{ github.event_name == 'pull_request' }}"
    steps:
      - uses: actions/download-artifact@v4
        id: artifacts
        with:
          name: ANARI-Docs
          path: _ANARI-Docs
      - run: |
          GIST_ID="$(gh gist list | grep "PR${{ github.event.pull_request.number }}" | awk '// { print $1 }')"
          gh gist delete ${GIST_ID}
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
      - run: |
          GIST_URL="$(gh gist create -d PR${{ github.event.pull_request.number }}  -p ${{ steps.artifacts.outputs.download-path }}/html/anspec.html)"
          MESSAGE="[Generated documentation](https://html-preview.github.io/?url=${GIST_URL}/raw/anspec.html)"
          gh pr -R ${{ github.repository }} comment --create-if-none --edit-last ${{ github.event.pull_request.number }} -b "${MESSAGE}"
        if: "${{ github.event.pull_request.action == 'opened' || github.event.pull_request.action == 'synchronize' }}"
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
